name: AWS Auth
description: Configure AWS credentials for GitHub Actions

runs:
  using: "composite"
  steps:
    - name: AWS Authentication
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ACCESS_ROLE }}
        role-session-name: Github
        aws-region: ${{ vars.AWS_REGION }}
